THOROUGH
main.py
--no-pointer-check --force-malloc-success

^VERIFICATION SUCCESSFUL$
