CORE
main.py

^ERROR: List out of bounds at\b
