THOROUGH
main.py
--force-malloc-success --no-pointer-check --no-bounds-check --unwind 9 --ir
^VERIFICATION SUCCESSFUL$
